# -*- coding: utf-8 -*-
"""Google Translator(Multi lang).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FcMMXCvUw0xF2S8jzWkaqZBOR8wsJkPP
"""

!pip install goslate

from goslate import Goslate

text = 'Hello friends. I am your teacher. I will teach you this course .'

trans = Goslate()

trans.translate(text = text,target_language='mr')

text2='नमस्कार मित्रांनो. मी तुमचा गुरू आहे. मी तुम्हाला हा कोर्स शिकवीन'
trans = Goslate()
trans.translate(text = text,target_language='hi')

text3='Hello friends. I am your teacher. I will teach you  AI course .'
trans= Goslate()
trans.translate(text=text3 ,target_language='bho')

lang= Goslate().get_languages()
lang

help(Goslate)

