# -*- coding: utf-8 -*-
"""GOOGLE TRANSLATOR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_llIN4P-EXo4uQS0FDF74eydDftZ7-So
"""

!pip install goslate

from goslate import Goslate

text = 'Hello friends. I am your teacher. I will teach you this course .'

trans = Goslate()

trans.translate(text = text,target_language='mr')

